### ISSUE TITLE
Hacking of Spotify work on iPad, but doesn't work on Mac.

### ISSUE THREAD

**Issue by FakeNewsNextOne** [Dokovic/Quantumult-X-ruleset-script#1]
Can you plz adapt Spotify on macOS? thanks a lot.

**Comment by FakeNewsNextOne** [comment]
I guess it's because the desktop Spotify using different links or authorization.

**Comment by Dokovic** [comment]
> Can you plz adapt Spotify on macOS? thanks a lot.

That's not a kinda similar work...sorry this module can only support mobile version

**Comment by FakeNewsNextOne** [comment]
> > Can you plz adapt Spotify on macOS? thanks a lot.
> 
> That's not a kinda similar work...sorry this module can only support mobile version

That's ok👌Your work on mobile version still helps a lot!
